<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
        <PackageReference Include="StackExchange.Redis" />
        <PackageReference Include="Apache.NMS" />
        <PackageReference Include="Apache.NMS.ActiveMQ" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\BuildingBlocks\RoomTrack.BuildingBlocks\RoomTrack.BuildingBlocks.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="RoomTrack.Analytics.API.Tests" />
    </ItemGroup>

</Project>
