// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomTrack.Accommodations.API.Infrastructure.Persistence;

#nullable disable

namespace RoomTrack.Accommodations.API.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AccommodationsDbContext))]
    [Migration("20261004065259_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BackendAwRoomTrack.API.Accommodations.Domain.Model.Aggregates.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("address");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("amenities");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("country");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<int>("HostId")
                        .HasColumnType("int")
                        .HasColumnName("host_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_hotels");

                    b.ToTable("hotels", (string)null);
                });

            modelBuilder.Entity("BackendAwRoomTrack.API.Accommodations.Domain.Model.Aggregates.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("amenities");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<int>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    b.Property<DateTimeOffset?>("MaintenanceAlertSentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("maintenance_alert_sent_at");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("number");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int")
                        .HasColumnName("room_type_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("StatusChangedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("status_changed_at");

                    b.HasKey("Id")
                        .HasName("p_k_rooms");

                    b.HasIndex("RoomTypeId")
                        .HasDatabaseName("i_x_rooms__room_type_id");

                    b.HasIndex("HotelId", "Number")
                        .IsUnique()
                        .HasDatabaseName("i_x_rooms__hotel_id__number");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("BackendAwRoomTrack.API.Accommodations.Domain.Model.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_amenities_catalogs");

                    b.ToTable("amenities_catalogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "General",
                            Name = "Wifi"
                        },
                        new
                        {
                            Id = 2,
                            Category = "General",
                            Name = "Piscina"
                        },
                        new
                        {
                            Id = 3,
                            Category = "General",
                            Name = "Gimnasio"
                        },
                        new
                        {
                            Id = 4,
                            Category = "General",
                            Name = "Restaurante"
                        },
                        new
                        {
                            Id = 5,
                            Category = "General",
                            Name = "Parking"
                        },
                        new
                        {
                            Id = 6,
                            Category = "General",
                            Name = "Spa"
                        },
                        new
                        {
                            Id = 7,
                            Category = "General",
                            Name = "Bar"
                        },
                        new
                        {
                            Id = 8,
                            Category = "General",
                            Name = "Desayuno"
                        });
                });

            modelBuilder.Entity("BackendAwRoomTrack.API.Accommodations.Domain.Model.Entities.HotelCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_hotel_categories");

                    b.ToTable("hotel_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hotel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Posada"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lodge"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hostal"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cabaña"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Resort"
                        });
                });

            modelBuilder.Entity("BackendAwRoomTrack.API.Accommodations.Domain.Model.Entities.RoomStatusChange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedByEmail")
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("changed_by_email");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("from_status");

                    b.Property<int>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("origin");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("p_k_room_status_changes");

                    b.HasIndex("RoomId", "ChangedAt")
                        .HasDatabaseName("i_x_room_status_changes__room_id__changed_at");

                    b.ToTable("room_status_changes", (string)null);
                });

            modelBuilder.Entity("BackendAwRoomTrack.API.Accommodations.Domain.Model.Entities.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_room_types");

                    b.ToTable("room_types", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("consumed");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("consumer_id");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivered");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiration_time");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("char(36)")
                        .HasColumnName("lock_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("char(36)")
                        .HasColumnName("message_id");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("int")
                        .HasColumnName("receive_count");

                    b.Property<DateTime>("Received")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("received");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("p_k_inbox_states");

                    b.HasAlternateKey("MessageId", "ConsumerId")
                        .HasName("a_k_inbox_states__message_id__consumer_id");

                    b.HasIndex("Delivered")
                        .HasDatabaseName("i_x_inbox_states__delivered");

                    b.ToTable("inbox_states");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("content_type");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("conversation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("destination_address");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("enqueue_time");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiration_time");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("fault_address");

                    b.Property<string>("Headers")
                        .HasColumnType("longtext")
                        .HasColumnName("headers");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("inbox_consumer_id");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("char(36)")
                        .HasColumnName("inbox_message_id");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("initiator_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("char(36)")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message_type");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("char(36)")
                        .HasColumnName("outbox_id");

                    b.Property<string>("Properties")
                        .HasColumnType("longtext")
                        .HasColumnName("properties");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("char(36)")
                        .HasColumnName("request_id");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("response_address");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_time");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("source_address");

                    b.HasKey("SequenceNumber")
                        .HasName("p_k_outbox_messages");

                    b.HasIndex("EnqueueTime")
                        .HasDatabaseName("i_x_outbox_messages__enqueue_time");

                    b.HasIndex("ExpirationTime")
                        .HasDatabaseName("i_x_outbox_messages__expiration_time");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("i_x_outbox_messages__outbox_id__sequence_number");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("i_x_outbox_messages__inbox_message_id__inbox_consumer_id__sequence_number");

                    b.ToTable("outbox_messages");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("outbox_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivered");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("char(36)")
                        .HasColumnName("lock_id");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version");

                    b.HasKey("OutboxId")
                        .HasName("p_k_outbox_states");

                    b.HasIndex("Created")
                        .HasDatabaseName("i_x_outbox_states__created");

                    b.ToTable("outbox_states");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("longtext")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("longtext")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("p_k_data_protection_keys");

                    b.ToTable("data_protection_keys");
                });

            modelBuilder.Entity("BackendAwRoomTrack.API.Accommodations.Domain.Model.Aggregates.Hotel", b =>
                {
                    b.OwnsOne("BackendAwRoomTrack.API.Accommodations.Domain.Model.ValueObjects.HotelPaymentSettings", "PaymentSettings", b1 =>
                        {
                            b1.Property<int>("HotelId")
                                .HasColumnType("int");

                            b1.Property<string>("AccountHolder")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("payment_account_holder");

                            b1.Property<string>("BankAccountCci")
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("payment_bank_account_cci");

                            b1.Property<string>("BankAccountNumber")
                                .HasMaxLength(30)
                                .HasColumnType("varchar(30)")
                                .HasColumnName("payment_bank_account_number");

                            b1.Property<string>("BankName")
                                .HasMaxLength(60)
                                .HasColumnType("varchar(60)")
                                .HasColumnName("payment_bank_name");

                            b1.Property<string>("PlinNumber")
                                .HasMaxLength(9)
                                .HasColumnType("varchar(9)")
                                .HasColumnName("payment_plin_number");

                            b1.Property<string>("YapeNumber")
                                .HasMaxLength(9)
                                .HasColumnType("varchar(9)")
                                .HasColumnName("payment_yape_number");

                            b1.HasKey("HotelId");

                            b1.ToTable("hotels");

                            b1.WithOwner()
                                .HasForeignKey("HotelId");
                        });

                    b.Navigation("PaymentSettings");
                });

            modelBuilder.Entity("BackendAwRoomTrack.API.Accommodations.Domain.Model.Aggregates.Room", b =>
                {
                    b.HasOne("BackendAwRoomTrack.API.Accommodations.Domain.Model.Aggregates.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_rooms_hotels__hotel_id");

                    b.HasOne("BackendAwRoomTrack.API.Accommodations.Domain.Model.Entities.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_rooms_room_types__room_type_id");

                    b.Navigation("Hotel");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("BackendAwRoomTrack.API.Accommodations.Domain.Model.Entities.RoomStatusChange", b =>
                {
                    b.HasOne("BackendAwRoomTrack.API.Accommodations.Domain.Model.Aggregates.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_room_status_changes_rooms__room_id");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId")
                        .HasConstraintName("f_k_outbox_messages__outbox_state__outbox_id");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId")
                        .HasConstraintName("f_k_outbox_messages_inbox_states__inbox_message_id__inbox_consumer_id");
                });

            modelBuilder.Entity("BackendAwRoomTrack.API.Accommodations.Domain.Model.Aggregates.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
