// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomTrack.Profiles.API.Infrastructure.Persistence;

#nullable disable

namespace RoomTrack.Profiles.API.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProfilesDbContext))]
    [Migration("20261004065313_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BackendAwRoomTrack.API.Marketing.Domain.Model.Aggregates.DemoRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccommodationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("accommodation_type");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<DateTimeOffset?>("FollowedUpAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("followed_up_at");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("hotel_name");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("job_title");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<string>("Phone")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("phone");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("profile");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("received_at");

                    b.Property<string>("ReferralSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("referral_source");

                    b.Property<string>("RoomsRange")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("rooms_range");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_demo_requests");

                    b.HasIndex("Email")
                        .HasDatabaseName("i_x_demo_requests__email");

                    b.HasIndex("Status", "ReceivedAt")
                        .HasDatabaseName("i_x_demo_requests__status__received_at");

                    b.ToTable("demo_requests", (string)null);
                });

            modelBuilder.Entity("BackendAwRoomTrack.API.Profiles.Infrastructure.Persistence.EFC.Entities.EmployeeCodeSequence", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("LastValue")
                        .HasColumnType("int")
                        .HasColumnName("last_value");

                    b.HasKey("Id")
                        .HasName("p_k_employee_code_sequences");

                    b.ToTable("employee_code_sequences", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastValue = 0
                        });
                });

            modelBuilder.Entity("BackendAwRoomTrack.Domain.Profiles.Domain.Model.Aggregates.GuestProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_guest_profiles");

                    b.HasIndex(new[] { "UserId" }, "ix_guest_profiles_user_id")
                        .IsUnique()
                        .HasDatabaseName("ix_guest_profiles_user_id");

                    b.ToTable("guest_profiles", (string)null);
                });

            modelBuilder.Entity("BackendAwRoomTrack.Domain.Profiles.Domain.Model.Aggregates.StaffProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("position");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("shift");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_staff_profiles");

                    b.HasIndex(new[] { "Code" }, "ix_staff_profiles_employee_code")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_profiles_employee_code");

                    b.HasIndex(new[] { "UserId" }, "ix_staff_profiles_user_id")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_profiles_user_id");

                    b.ToTable("staff_profiles", (string)null);
                });

            modelBuilder.Entity("BackendAwRoomTrack.Domain.Profiles.Domain.Model.Entities.StaffAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("scope");

                    b.Property<Guid>("StaffProfileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("staff_profile_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("TargetId")
                        .HasColumnType("int")
                        .HasColumnName("target_id");

                    b.HasKey("Id")
                        .HasName("p_k_staff_assignments");

                    b.HasIndex(new[] { "StaffProfileId" }, "ix_staff_assignments_staff_profile_id")
                        .HasDatabaseName("ix_staff_assignments_staff_profile_id");

                    b.HasIndex(new[] { "TargetId" }, "ix_staff_assignments_target_id")
                        .HasDatabaseName("ix_staff_assignments_target_id");

                    b.ToTable("staff_assignments", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("consumed");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("consumer_id");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivered");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiration_time");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("char(36)")
                        .HasColumnName("lock_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("char(36)")
                        .HasColumnName("message_id");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("int")
                        .HasColumnName("receive_count");

                    b.Property<DateTime>("Received")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("received");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("p_k_inbox_states");

                    b.HasAlternateKey("MessageId", "ConsumerId")
                        .HasName("a_k_inbox_states__message_id__consumer_id");

                    b.HasIndex("Delivered")
                        .HasDatabaseName("i_x_inbox_states__delivered");

                    b.ToTable("inbox_states");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("content_type");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("conversation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("destination_address");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("enqueue_time");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiration_time");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("fault_address");

                    b.Property<string>("Headers")
                        .HasColumnType("longtext")
                        .HasColumnName("headers");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("inbox_consumer_id");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("char(36)")
                        .HasColumnName("inbox_message_id");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("initiator_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("char(36)")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message_type");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("char(36)")
                        .HasColumnName("outbox_id");

                    b.Property<string>("Properties")
                        .HasColumnType("longtext")
                        .HasColumnName("properties");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("char(36)")
                        .HasColumnName("request_id");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("response_address");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_time");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("source_address");

                    b.HasKey("SequenceNumber")
                        .HasName("p_k_outbox_messages");

                    b.HasIndex("EnqueueTime")
                        .HasDatabaseName("i_x_outbox_messages__enqueue_time");

                    b.HasIndex("ExpirationTime")
                        .HasDatabaseName("i_x_outbox_messages__expiration_time");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("i_x_outbox_messages__outbox_id__sequence_number");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("i_x_outbox_messages__inbox_message_id__inbox_consumer_id__sequence_number");

                    b.ToTable("outbox_messages");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("outbox_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivered");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("char(36)")
                        .HasColumnName("lock_id");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_version");

                    b.HasKey("OutboxId")
                        .HasName("p_k_outbox_states");

                    b.HasIndex("Created")
                        .HasDatabaseName("i_x_outbox_states__created");

                    b.ToTable("outbox_states");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("longtext")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("longtext")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("p_k_data_protection_keys");

                    b.ToTable("data_protection_keys");
                });

            modelBuilder.Entity("BackendAwRoomTrack.Domain.Profiles.Domain.Model.Aggregates.GuestProfile", b =>
                {
                    b.OwnsOne("BackendAwRoomTrack.Domain.Profiles.Domain.Model.ValueObjects.StreetAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("GuestProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("address_country");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("address_street");

                            b1.HasKey("GuestProfileId");

                            b1.ToTable("guest_profiles");

                            b1.WithOwner()
                                .HasForeignKey("GuestProfileId");
                        });

                    b.OwnsOne("BackendAwRoomTrack.Domain.Profiles.Domain.Model.ValueObjects.IdentificationDocument", "Document", b1 =>
                        {
                            b1.Property<Guid>("GuestProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("document_number");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("document_type");

                            b1.HasKey("GuestProfileId");

                            b1.HasIndex(new[] { "Type", "Number" }, "ix_guest_profiles_document")
                                .IsUnique();

                            b1.ToTable("guest_profiles");

                            b1.WithOwner()
                                .HasForeignKey("GuestProfileId");
                        });

                    b.OwnsOne("BackendAwRoomTrack.Domain.Profiles.Domain.Model.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("GuestProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("email_address");

                            b1.HasKey("GuestProfileId");

                            b1.HasIndex(new[] { "Address" }, "ix_guest_profiles_email_address")
                                .IsUnique();

                            b1.ToTable("guest_profiles");

                            b1.WithOwner()
                                .HasForeignKey("GuestProfileId");
                        });

                    b.OwnsOne("BackendAwRoomTrack.Domain.Profiles.Domain.Model.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("GuestProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("GuestProfileId");

                            b1.ToTable("guest_profiles");

                            b1.WithOwner()
                                .HasForeignKey("GuestProfileId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Document");

                    b.Navigation("Email");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("BackendAwRoomTrack.Domain.Profiles.Domain.Model.Aggregates.StaffProfile", b =>
                {
                    b.OwnsOne("BackendAwRoomTrack.Domain.Profiles.Domain.Model.ValueObjects.StreetAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("StaffProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("address_country");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("address_street");

                            b1.HasKey("StaffProfileId");

                            b1.ToTable("staff_profiles");

                            b1.WithOwner()
                                .HasForeignKey("StaffProfileId");
                        });

                    b.OwnsOne("BackendAwRoomTrack.Domain.Profiles.Domain.Model.ValueObjects.IdentificationDocument", "Document", b1 =>
                        {
                            b1.Property<Guid>("StaffProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("document_number");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("document_type");

                            b1.HasKey("StaffProfileId");

                            b1.ToTable("staff_profiles");

                            b1.WithOwner()
                                .HasForeignKey("StaffProfileId");
                        });

                    b.OwnsOne("BackendAwRoomTrack.Domain.Profiles.Domain.Model.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("StaffProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("email_address");

                            b1.HasKey("StaffProfileId");

                            b1.HasIndex(new[] { "Address" }, "ix_staff_profiles_email_address")
                                .IsUnique();

                            b1.ToTable("staff_profiles");

                            b1.WithOwner()
                                .HasForeignKey("StaffProfileId");
                        });

                    b.OwnsOne("BackendAwRoomTrack.Domain.Profiles.Domain.Model.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("StaffProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("StaffProfileId");

                            b1.ToTable("staff_profiles");

                            b1.WithOwner()
                                .HasForeignKey("StaffProfileId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Document");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("BackendAwRoomTrack.Domain.Profiles.Domain.Model.Entities.StaffAssignment", b =>
                {
                    b.HasOne("BackendAwRoomTrack.Domain.Profiles.Domain.Model.Aggregates.StaffProfile", null)
                        .WithMany("Assignments")
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_staff_assignments_staff_profiles__staff_profile_id");

                    b.OwnsOne("BackendAwRoomTrack.Domain.Profiles.Domain.Model.ValueObjects.DateRange", "Period", b1 =>
                        {
                            b1.Property<Guid>("StaffAssignmentId")
                                .HasColumnType("char(36)");

                            b1.Property<DateOnly?>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("end_date");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("start_date");

                            b1.HasKey("StaffAssignmentId");

                            b1.ToTable("staff_assignments");

                            b1.WithOwner()
                                .HasForeignKey("StaffAssignmentId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId")
                        .HasConstraintName("f_k_outbox_messages__outbox_state__outbox_id");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId")
                        .HasConstraintName("f_k_outbox_messages_inbox_states__inbox_message_id__inbox_consumer_id");
                });

            modelBuilder.Entity("BackendAwRoomTrack.Domain.Profiles.Domain.Model.Aggregates.StaffProfile", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
