<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\BuildingBlocks\RoomTrack.BuildingBlocks\RoomTrack.BuildingBlocks.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="RoomTrack.Profiles.API.Tests" />
    </ItemGroup>

</Project>
